#端口
server:
  port: 8080
#spring的配置
spring:
  application:
    name: application
  #数据源的配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/open-his?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: liqinshe123
    #注入数据源的类型   默认的为HikariDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 20
      min-idle: 5
      validation-query: select x
      initial-size: 3
      max-wait: 5000
      stat-view-servlet:
        #        login-username: root
        #        login-password: 123456
        allow:
        deny:
        url-pattern: /druid/*
        enabled: true  #启用数据源监控
  #配置redis
  redis:
    port: 6379
    host: 119.29.76.22   #116.45.1.15
    password: liqinshe123
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

#shiro配置
shiro:
  anon-urls:
    - /login/doLogin*
    - /login/captcha*
    - /login/logout*
    - /druid/**
  authc-urls:
    - /**
#mybatisplus的配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*Mapper.xml
  global-config:
    db-config:
      id-type: auto
#fastdfs的配置
fdfs:
  so-timeout: 2500       # 读取时间
  connect-timeout: 600   # 连接超时时间
  thumb-image:           # 缩略图
    width: 100
    height: 100
  tracker-list:          # tracker服务配置地址列表
    - 119.29.76.22:22122
upload:
  base-url: http://119.29.76.22:8888
  allow-types:
    - image/jpg
    - image/jpeg
    - image/png
    - image/bmp
#dubbo配置
dubbo:
  application:
    name: his-system-web-service
  registry:
    address: zookeeper://119.29.76.22:2181
    timeout: 60000
  consumer:
    check: false